In [2]:
import os
import numpy as np
import pandas as pd
import glob

In [5]:
path = os.getcwd()
files = os.listdir(path)
files,path

(['.ipynb_checkpoints',
  'Electricity Data',
  'Fault_pred.ipynb',
  'load_neat_params.ipynb',
  'test.ipynb',
  'test.txt'],
 'D:\\Neat')

In [7]:
path =r'D:\Neat\Electricity Data\2018\LOG REPORT APRIL 2018\01.04.18'
allFiles = glob.glob(path + "/*.xls")
allFiles

['D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\West .xls']

In [3]:
path2 = r'D:\Neat\Electricity Data\2018\LOG REPORT APRIL 2018'
allf = glob.glob(path2 + "/*/*.xls")
allf

['D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\01.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\02.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\02.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\02.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\02.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\03.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\03.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\03.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\03.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\04.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\04.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\04.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\04.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\05.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\05.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\05.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\05.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\06.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\06.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\06.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\06.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\07.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\07.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\07.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\07.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\08.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\08.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\08.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\08.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\09.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\09.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\09.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\09.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\10.04.18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\10.04.18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\10.04.18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\10.04.18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\11-04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\11-04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\11-04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\11-04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\12.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\12.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\12.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\12.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\13.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\13.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\13.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\13.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\14.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\14.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\14.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\14.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\15.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\15.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\15.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\15.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\16.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\16.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\16.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\16.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\17.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\17.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\17.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\17.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\18.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\18.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\18.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\18.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\19.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\19.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\19.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\19.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\20.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\20.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\20.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\20.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\21.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\21.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\21.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\21.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\22.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\22.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\22.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\22.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\23.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\23.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\23.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\23.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\24.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\24.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\24.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\24.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\25.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\25.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\25.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\25.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\26.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\26.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\26.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\26.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\27.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\27.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\27.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\27.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\28.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\28.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\28.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\28.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\29.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\29.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\29.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\29.04-18\\West .xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\30.04-18\\South-1.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\30.04-18\\SOUTH-3.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\30.04-18\\South-II.xls',
 'D:\\Neat\\Electricity Data\\2018\\LOG REPORT APRIL 2018\\30.04-18\\West .xls']

In [64]:
all_data = pd.DataFrame()
for f in allf:
    df = pd.read_excel(f,'ALL',header=None)
    all_data = all_data.append(df[1:],ignore_index=True)

In [65]:
all_data.iloc[5575:,100:]
all_data.iloc[:,:]

,0,1,2,3,4,5,6,7,8,9,...,98,99,100,101,102,103,104,105,106,107
0,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,Battery,AMPs,...,18.07,18.0395,18.07,18.0395,18.07,18.07,18.07,18.07,18.1005,2018-04-01 03:00:00
1,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,Battery,Volts,...,55.5559,55.5559,55.5559,55.5559,55.5559,55.5559,55.5559,55.5559,55.739,2018-04-01 05:00:00
2,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,NEHRU STADIUM CKT-1,AMPs,...,82.1061,79.3323,79.4924,78.8581,77.7402,77.7402,77.7402,77.7402,86.7252,2018-04-01 20:00:00
3,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,NEHRU STADIUM CKT-1,KV,...,32.9722,32.8967,33.0952,32.9921,32.9902,32.9902,32.9902,32.9902,33.8179,2018-04-01 04:00:00
4,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,NEHRU STADIUM CKT-1,PF,...,-0.972117,-0.973337,-0.972156,-0.973869,-0.9742,-0.9742,-0.9742,-0.9742,-0.960099,2018-04-01 07:15:00
5,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,LODHI ROAD CKT 2,AMPs,...,115.547,111.142,112.562,108.438,103.732,103.732,103.732,103.732,118.547,2018-04-01 19:15:00
6,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,LODHI ROAD CKT 2,KV,...,33.6948,33.8581,33.705,33.7871,33.8087,33.8087,33.8087,33.8087,34.5499,2018-04-01 04:00:00
7,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,LODHI ROAD CKT 2,PF,...,-0.97089,-0.973057,-0.972709,-0.974297,-0.974874,-0.974874,-0.974874,-0.974874,-0.960243,2018-04-01 06:00:00
8,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,KILOKARI-RKP1,AMPs,...,6e-06,0,0,0,0,0,0,0,6e-06,2018-04-01 14:30:00
9,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,KILOKARI-RKP1,KV,...,33.3494,33.4183,33.3949,33.5149,33.5127,33.5127,33.5127,33.5127,34.2904,2018-04-01 04:00:00
10,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,KILOKARI-RKP1,PF,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,2018-04-01 00:00:00
11,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,NEHRU STADIUM CKT-2,AMPs,...,111.401,112.483,135.806,111.327,111.648,111.648,111.648,111.648,139.587,2018-04-01 20:00:00
12,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,NEHRU STADIUM CKT-2,KV,...,33.1256,33.0176,33.2327,33.0987,33.0999,33.0999,33.0999,33.0999,33.9223,2018-04-01 04:00:00
13,2018-04-01 00:00:00,DEFENCE COLONY,NaN,NaN,NaN,NaN,NaN,NaN,NEHRU STADIUM CKT-2,PF,...,0.832972,0.834276,0.828691,-0.98255,-0.982737,-0.982737,-0.982737,0.809946,0.869781,2018-04-01 20:00:00
14,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,1,NaN,NaN,NaN,NaN,HV1,AMPs,...,81.7924,79.2024,79.3484,78.743,76.9875,76.9875,76.9875,76.9875,86.6564,2018-04-01 20:15:00
15,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,1,NaN,NaN,NaN,NaN,HV1,KV,...,25.8323,25.9621,25.8633,25.9221,25.9292,25.9292,25.9292,25.9292,26.621,2018-04-01 04:00:00
16,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,1,NaN,NaN,NaN,NaN,TR1,WTI,...,43.5896,43.5896,43.5896,43.5896,42.4909,42.4909,42.4909,42.4909,51.3718,2018-04-01 12:00:00
17,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,1,NaN,NaN,NaN,NaN,TR1,OTI,...,42.3994,42.3994,41.4838,41.4838,41.4838,41.4838,41.4838,41.4838,48.442,2018-04-01 12:00:00
18,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,1,NaN,NaN,NaN,NaN,TR1,TAP POSITION,...,2.99713,2.99713,2.99713,2.99713,2.99713,2.99713,2.99713,2.99713,2.99713,2018-04-01 00:00:00
19,2018-04-01 00:00:00,DEFENCE COLONY,25 MVA,NaN,2,NaN,NaN,NaN,HV2,AMPs,...,115.79,110.899,112.018,108.673,103.402,103.402,103.402,103.402,118.582,2018-04-01 19:15:00
20,2018-04-01 00:00:00,DEFENCE COLONY,25 MVA,NaN,2,NaN,NaN,NaN,HV2,KV,...,25.3848,25.5267,25.4125,25.4512,25.4738,25.4738,25.4738,25.4738,26.167,2018-04-01 04:00:00
21,2018-04-01 00:00:00,DEFENCE COLONY,25 MVA,NaN,2,NaN,NaN,NaN,TR2,WTI,...,41.6669,40.9803,40.9803,40.7514,40.7514,40.8429,40.8429,40.8429,51.1887,2018-04-01 15:00:00
22,2018-04-01 00:00:00,DEFENCE COLONY,25 MVA,NaN,2,NaN,NaN,NaN,TR2,OTI,...,44.8714,44.2763,44.1847,44.0474,43.9558,43.9558,43.9558,43.9558,53.2487,2018-04-01 15:00:00
23,2018-04-01 00:00:00,DEFENCE COLONY,25 MVA,NaN,2,NaN,NaN,NaN,TR2,TAP POSITION,...,3.01227,3.01227,3.01227,3.01227,3.01227,3.01227,3.01227,3.01227,3.0611,2018-04-01 00:00:00
24,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,NaN,NaN,3,NaN,NaN,HV3,AMPs,...,135.938,112.898,136.573,111.429,110.853,110.853,110.853,110.853,139.903,2018-04-01 20:00:00
25,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,NaN,NaN,3,NaN,NaN,HV3,KV,...,33.0064,32.8967,33.1373,32.9965,32.9847,32.9847,32.9847,32.9847,33.8416,2018-04-01 04:00:00
26,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,NaN,NaN,3,NaN,NaN,TR3,WTI,...,46.7483,46.1989,46.3362,45.9243,45.9243,46.1074,46.1074,46.1074,52.6078,2018-04-01 14:00:00
27,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,NaN,NaN,3,NaN,NaN,TR3,OTI,...,43.0403,42.9029,42.9029,42.7198,42.7198,42.7198,42.5367,42.5367,49.1745,2018-04-01 14:00:00
28,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,NaN,NaN,3,NaN,NaN,TR3,TAP POSITION,...,2.98737,2.99225,2.98737,2.99225,2.98737,2.98737,2.98737,2.98737,2.99225,2018-04-01 01:15:00
29,2018-04-01 00:00:00,DEFENCE COLONY,20 MVA,1,NaN,NaN,NaN,NaN,LV1,AMPs,...,252.464,245.262,246.209,241.2,235.423,235.423,235.423,235.423,267.266,2018-04-01 20:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164590,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,LV1,AMPs,...,249.168,249.168,249.168,249.168,1900-09-05 04:01:55.114000,1900-09-05 04:01:55.114000,1900-09-05 04:01:55.114000,1900-10-06 13:26:23.827000,1902-05-27 05:34:04.368000,00:00:00
164591,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,LV2,PF,...,-0.988225,-0.988225,-0.988225,-0.988225,1899-12-30 00:16:57.360000,1899-12-30 00:16:57.360000,1899-12-30 00:16:57.360000,1899-12-30 00:15:50.746000,1899-12-30 00:31:27.667000,00:00:00
164592,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,LV2,KV,...,10.0327,10.0327,10.0327,10.0327,1900-01-10 00:47:01.922000,1900-01-10 00:47:01.922000,1900-01-10 00:47:01.922000,1900-01-09 21:43:06.516000,1900-01-10 09:50:10.584000,00:00:00
164593,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,LV2,AMPs,...,564.872,564.872,564.872,564.872,1901-07-17 20:56:13.200000,1901-07-17 20:56:13.200000,1901-07-17 20:56:13.200000,1901-12-03 13:22:26.486000,1901-12-03 13:22:26.486000,00:00:00
164594,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,1,0,0,0,Local Trf.1,AMPs,...,15.848,15.848,15.848,15.848,1900-01-15 20:21:07.286000,1900-01-15 20:21:07.286000,1900-01-14 23:48:28.886000,00:00:00,1900-01-16 04:13:26.486000,00:00:00
164595,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,SPARE,PF,...,0,0,0,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
164596,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,SPARE,AMPs,...,0,0,0,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
164597,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,NAND VIHAR,PF,...,0.9871,0.9871,0.9871,0.9871,23:41:25.440000,23:41:25.440000,23:41:25.440000,23:40:07.680000,23:49:03.360000,00:00:00
164598,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,NAND VIHAR,AMPs,...,150.16,150.16,150.16,150.16,1900-05-29 03:50:24.346000,1900-05-29 03:50:24.346000,1900-05-29 03:50:24.346000,1900-06-23 04:59:31.891000,1900-06-23 04:59:31.891000,00:00:00
164599,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,PP SEC-17,PF,...,0.9848,0.9848,0.9848,0.9848,23:38:06.720000,23:38:06.720000,23:38:06.720000,23:55:40.800000,23:57:59.040000,00:00:00
164600,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,PP SEC-17,AMPs,...,79.4,79.4,79.4,79.4,1900-03-19 09:36:00.173000,1900-03-19 09:36:00.173000,1900-03-19 09:36:00.173000,1900-03-15 09:24:29.318000,1900-03-19 09:36:00.173000,00:00:00
164601,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,5MGD SS-1,PF,...,0.0536,0.0536,0.0536,0.0536,01:17:11.040000,01:17:11.040000,01:17:11.040000,1899-12-30 22:41:22.560000,23:59:34.080000,00:00:00
164602,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,5MGD SS-1,AMPs,...,1.592,1.592,1.592,1.592,1900-01-01 14:12:28.800000,1900-01-01 14:12:28.800000,1900-01-01 14:12:28.800000,1900-01-01 14:12:28.800000,1900-01-23 00:23:02.486000,00:00:00
164603,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,DELHI JUDICIAL-1 SEC-14,PF,...,0.9841,0.9841,0.9841,0.9841,23:37:06.240000,23:37:06.240000,23:37:06.240000,22:55:03.360000,23:38:06.720000,00:00:00
164604,2018-04-27 00:00:00,220KV PPK-2,20 MVA,1,0,0,0,0,DELHI JUDICIAL-1 SEC-14,AMPs,...,15.408,15.408,15.408,15.408,1900-01-15 09:47:31.286000,1900-01-15 09:47:31.286000,1900-01-15 09:47:31.286000,1900-01-24 14:35:31.373000,1900-02-14 00:23:02.659000,00:00:00
164605,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,Local Trf.2,AMPs,...,0,0,0,0,00:00:00,00:00:00,00:00:00,00:00:00,1900-01-02 13:49:26.400000,00:00:00
164606,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,DMRC SHOPING COMPLEX,PF,...,0.9908,0.9908,0.9908,0.9908,23:46:45.120000,23:46:45.120000,23:46:45.120000,23:48:02.880000,23:56:24,00:00:00
164607,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,DMRC SHOPING COMPLEX,AMPs,...,120.416,120.416,120.416,120.416,1900-04-29 09:59:03.091000,1900-04-29 09:59:03.091000,1900-04-29 09:59:03.091000,1900-05-21 17:51:21.859000,1900-05-21 17:51:21.859000,00:00:00
164608,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,DELHI JUDICIAL-2 SEC-14,PF,...,0.98,0.98,0.98,0.98,23:31:12,23:31:12,23:31:12,23:32:03.840000,23:54:31.680000,00:00:00
164609,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,DELHI JUDICIAL-2 SEC-14,AMPs,...,193.032,193.032,193.032,193.032,1900-07-11 00:46:05.923000,1900-07-11 00:46:05.923000,1900-07-11 00:46:05.923000,1900-09-16 14:35:31.373000,1900-09-16 14:35:31.373000,00:00:00
164610,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,KAKROLLA VILLAGE,PF,...,0.9807,0.9807,0.9807,0.9807,23:32:12.480000,23:32:12.480000,23:32:12.480000,23:33:30.240000,23:33:30.240000,00:00:00
164611,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,KAKROLLA VILLAGE,AMPs,...,125.328,125.328,125.328,125.328,1900-05-04 07:52:19.459000,1900-05-04 07:52:19.459000,1900-05-04 07:52:19.459000,1900-06-13 10:56:39.178000,1900-06-13 10:56:39.178000,00:00:00
164612,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,DMRC STAFF QUARTER,PF,...,0.9834,0.9834,0.9834,0.9834,23:36:05.760000,23:36:05.760000,23:36:05.760000,23:46:27.840000,23:56:06.720000,00:00:00
164613,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,DMRC STAFF QUARTER,AMPs,...,69.024,69.024,69.024,69.024,1900-03-09 00:34:33.773000,1900-03-09 00:34:33.773000,1900-03-09 00:34:33.773000,1900-04-04 11:54:14.573000,1900-04-04 11:54:14.573000,00:00:00
164614,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,5MGD SS-2,PF,...,-0.9938,-0.9938,-0.9938,-0.9938,1899-12-30 00:08:55.680000,1899-12-30 00:08:55.680000,1899-12-30 00:08:55.680000,1899-12-30 00:03:10.080000,23:57:50.400000,00:00:00
164615,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,5MGD SS-2,AMPs,...,11.12,11.12,11.12,11.12,1900-01-11 02:52:48.086000,1900-01-11 02:52:48.086000,1900-01-11 02:52:48.086000,1900-01-13 14:47:02.400000,1900-01-17 00:34:33.600000,00:00:00
164616,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,EROS METRO MALL SEC-14 + 736 EWS SEC-16,PF,...,0,0,0,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
164617,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,EROS METRO MALL SEC-14 + 736 EWS SEC-16,AMPs,...,0,0,0,0,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
164618,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,GGSIPU + SEC-16B PKT-1,PF,...,-0.962293,-0.962293,-0.962293,-0.962293,1899-12-30 00:54:17.885000,1899-12-30 00:54:17.885000,1899-12-30 00:54:17.885000,1899-12-30 00:54:17.885000,1899-12-30 00:54:17.885000,00:00:00
164619,2018-04-27 00:00:00,220KV PPK-2,20 MVA,0,2,0,0,0,GGSIPU + SEC-16B PKT-1,AMPs,...,57.7086,57.7086,57.7086,57.7086,1900-02-26 17:00:21.312000,1900-02-26 17:00:21.312000,1900-02-26 17:00:21.312000,1900-02-26 17:00:21.312000,1900-02-26 17:00:21.312000,00:00:00